// ============================================================
// コマンドリファレンス(統合版 / Java版の構文比較つき)
// ============================================================

const COMMAND_REF = [
  {
    name: "effect",
    summary: "ポーション効果を付与・解除する",
    java: "effect give <対象> <効果> [秒数] [レベル] [パーティクル非表示]\neffect clear <対象>",
    bedrock: "effect <対象> <効果> [秒数] [レベル] [パーティクル非表示]\neffect <対象> clear",
    example: "effect give @a minecraft:night_vision 60 0 true(Java版)",
    desc: "レベルは0から数えます(0=レベル1)。Java版は give/clear のサブコマンドが必要です。",
  },
  {
    name: "execute",
    summary: "条件付きで他のコマンドを実行する",
    java: "execute as <対象> at <対象> if entity <セレクタ> run <コマンド>\nexecute if block <座標> <ブロック> run <コマンド>",
    bedrock: "execute as <対象> at <対象> if entity <セレクタ> run <コマンド>\nexecute if block <座標> <ブロック> run <コマンド>",
    example: "execute as @a at @s if block ~ ~-1 ~ gold_block run effect @s levitation 1 4",
    desc: "統合版も1.19.50以降は新execute構文に対応し、書き方はほぼ同じです。ただしセレクタの距離指定はJava版が distance=..5、統合版が r=5 と異なります。",
  },
  {
    name: "give",
    summary: "アイテムを与える",
    java: "give <対象> <アイテム> [個数]",
    bedrock: "give <対象> <アイテム> [個数] [データ値]",
    example: "give @p diamond 64",
    desc: "アイテムIDは両エディションでほぼ共通です。",
  },
  {
    name: "tp / teleport",
    summary: "テレポートさせる",
    java: "tp <対象> <x> <y> <z>\ntp <対象> <対象>",
    bedrock: "tp <対象> <x> <y> <z>\ntp <対象> <対象>",
    example: "tp @a 100 64 100",
    desc: "「~」で相対座標、Java版は「^」でローカル座標も使えます。",
  },
  {
    name: "summon",
    summary: "エンティティを召喚する",
    java: "summon <エンティティ> [x y z] [NBT]",
    bedrock: "summon <エンティティ> [x y z] [イベント/名前]",
    example: "summon zombie ~ ~1 ~",
    desc: "Java版はNBTタグで細かいカスタムが可能。統合版はスポーンイベントを指定できます。",
  },
  {
    name: "time",
    summary: "時間を変更・確認する",
    java: "time set <day|noon|night|midnight|数値>\ntime add <数値>",
    bedrock: "time set <day|noon|sunrise|sunset|night|midnight|数値>\ntime add <数値>",
    example: "time set night",
    desc: "数値は0=朝6時、6000=正午、13000=夜、18000=真夜中です。",
  },
  {
    name: "weather",
    summary: "天気を変更する",
    java: "weather <clear|rain|thunder> [秒数]",
    bedrock: "weather <clear|rain|thunder> [秒数]",
    example: "weather thunder",
    desc: "両エディションで同じ書き方です。",
  },
  {
    name: "title",
    summary: "画面に大きな文字を表示する",
    java: "title <対象> <title|subtitle|actionbar> <JSONテキスト>",
    bedrock: "title <対象> <title|subtitle|actionbar> <文字>\ntitleraw <対象> <title|…> <rawtext JSON>",
    example: 'title @a title {"text":"ようこそ","color":"gold"}(Java版)',
    desc: "Java版はJSON形式が必須。統合版は普通の文字でOKで、色は§コード(例: §c赤)を使います。",
  },
  {
    name: "particle",
    summary: "パーティクルを表示する",
    java: "particle <パーティクル> [x y z] [dx dy dz] [速度] [個数]",
    bedrock: "particle <パーティクル> <x y z>",
    example: "particle minecraft:heart ~ ~1 ~ 0.5 0.5 0.5 0 10(Java版)",
    desc: "パーティクル名がエディションで大きく異なります(例: Java版 heart → 統合版 minecraft:heart_particle)。",
  },
  {
    name: "playsound",
    summary: "効果音を鳴らす",
    java: "playsound <サウンド> <チャンネル> <対象> [x y z] [音量] [ピッチ]",
    bedrock: "playsound <サウンド> [対象] [x y z] [音量] [ピッチ]",
    example: "playsound random.levelup @a(統合版)",
    desc: "サウンド名がエディションで異なります(例: Java版 entity.player.levelup → 統合版 random.levelup)。",
  },
  {
    name: "gamemode",
    summary: "ゲームモードを変更する",
    java: "gamemode <survival|creative|adventure|spectator> [対象]",
    bedrock: "gamemode <survival|creative|adventure|spectator|数字> [対象]",
    example: "gamemode creative @s",
    desc: "統合版は 0(サバイバル)や 1(クリエイティブ)の数字指定もできます。",
  },
  {
    name: "gamerule",
    summary: "ワールドのルールを変更する",
    java: "gamerule <ルール名> <値>",
    bedrock: "gamerule <ルール名> <値>",
    example: "gamerule keepInventory true",
    desc: "keepInventory(死んでもアイテム保持)、doDaylightCycle(時間停止)、mobGriefing(クリーパーの破壊防止)などが人気です。",
  },
  {
    name: "setblock",
    summary: "ブロックを1つ設置する",
    java: "setblock <x y z> <ブロック> [replace|keep|destroy]",
    bedrock: "setblock <x y z> <ブロック> [replace|keep|destroy]",
    example: "setblock ~ ~2 ~ diamond_block",
    desc: "destroy を付けると元のブロックを壊した扱いになりドロップします。",
  },
  {
    name: "fill",
    summary: "範囲をブロックで埋める",
    java: "fill <x1 y1 z1> <x2 y2 z2> <ブロック> [replace|hollow|outline|keep|destroy]",
    bedrock: "fill <x1 y1 z1> <x2 y2 z2> <ブロック> [replace|hollow|outline|keep|destroy]",
    example: "fill ~ ~ ~ ~10 ~5 ~10 air(整地)",
    desc: "hollow は中を空洞に、outline は外枠だけ埋めます。一度に埋められる量には上限があります。",
  },
  {
    name: "kill",
    summary: "エンティティを消す",
    java: "kill [対象]",
    bedrock: "kill [対象]",
    example: "kill @e[type=item](アイテム掃除)",
    desc: "@e[type=◯◯] と組み合わせて特定のモブだけ消せます。",
  },
  {
    name: "clear",
    summary: "インベントリからアイテムを消す",
    java: "clear [対象] [アイテム] [個数]",
    bedrock: "clear [対象] [アイテム] [データ値] [個数]",
    example: "clear @p diamond",
    desc: "アイテムを指定しなければ全部消えます。",
  },
  {
    name: "scoreboard",
    summary: "スコア(点数)を管理する",
    java: "scoreboard objectives add <名前> <種類> [表示名]\nscoreboard players set <対象> <名前> <値>",
    bedrock: "scoreboard objectives add <名前> dummy [表示名]\nscoreboard players set <対象> <名前> <値>",
    example: "scoreboard objectives add point dummy ポイント",
    desc: "Java版は kill数などを自動計測する種類も指定可能。統合版は dummy のみで、コマンドで加点します。",
  },
  {
    name: "function",
    summary: "ファイルに書いたコマンドをまとめて実行する",
    java: "function <名前空間>:<関数名>",
    bedrock: "function <関数名>",
    example: "function mypack:start(Java版)/ function start(統合版)",
    desc: "このアプリで書き出した .mcfunction はこのコマンドで実行します!",
  },
  {
    name: "tellraw",
    summary: "チャットに装飾付きメッセージを送る",
    java: 'tellraw <対象> {"text":"こんにちは","color":"aqua"}',
    bedrock: 'tellraw <対象> {"rawtext":[{"text":"こんにちは"}]}',
    example: 'tellraw @a {"text":"イベント開始!","color":"gold"}(Java版)',
    desc: "JSON形式の書き方がエディションで異なります。統合版は rawtext で囲みます。",
  },
  {
    name: "locate",
    summary: "構造物やビオームの場所を調べる",
    java: "locate structure <構造物>\nlocate biome <ビオーム>",
    bedrock: "locate structure <構造物>\nlocate biome <ビオーム>",
    example: "locate structure village",
    desc: "村・要塞・古代都市などの座標が分かります。",
  },
  {
    name: "enchant",
    summary: "持っているアイテムにエンチャントする",
    java: "enchant <対象> <エンチャント> [レベル]",
    bedrock: "enchant <対象> <エンチャント> [レベル]",
    example: "enchant @s sharpness 5",
    desc: "手に持っているアイテムが対象です。通常の上限を超えるレベルは付けられません。",
  },
  {
    name: "xp / experience",
    summary: "経験値を与える",
    java: "experience add <対象> <量> [levels|points]\nxp <量>L <対象>",
    bedrock: "xp <量> <対象>(ポイント)\nxp <量>L <対象>(レベル)",
    example: "xp 10L @p",
    desc: "「L」を付けるとレベル単位で与えられます。",
  },
  {
    name: "setworldspawn / spawnpoint",
    summary: "リスポーン地点を設定する",
    java: "setworldspawn [x y z](ワールド全体)\nspawnpoint [対象] [x y z](個人)",
    bedrock: "setworldspawn [x y z]\nspawnpoint [対象] [x y z]",
    example: "spawnpoint @a 0 70 0",
    desc: "ミニゲームの復活地点づくりに便利です。",
  },
];
